### ISSUE TITLE
Problem with GDB 7.4.1

### ISSUE THREAD

**Issue by paulharris** [ruediger/Boost-Pretty-Printer#24]
Hi,

The main branch seems to be ok,
but @mateidavid 's merge_attempt branch has problems importing into GDB 7.4.1, with this error:

Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "/path/Boost-Pretty-Printer/boost/utils.py", line 646, in register_printers
    gdb.types.register_type_printer(obj, tp)
AttributeError: 'module' object has no attribute 'register_type_printer'

Is this something fixable, or is this GDB simply too old?
Something that should be documented?

cheers,
Paul

**Comment by mateidavid** [comment]
Hi, 7.4.1, wow :) When I last ran the tests 9 months ago, I used 7.6.2 - 7.9, and today we're at 7.10. And gcc is advancing, too. The problem of course is that the gdb printing API and in fact the entire Python API has been slowly but surely accumulating changes between versions. I don't see much motivation going backwards. I didn't even check 7.10 works because I'm not using it. Although even that is not a given, I might be more inclined to keep things working in newer versions than in older ones.

Regarding that specific error, it's about type name printing, not value printing. If you care about the latter, try editing `utils.py` and disabling the type printer registration at https://github.com/mateidavid/Boost-Pretty-Printer/blob/merge-attempt/boost/utils.py#L646. Mind you, you might hit other API differences, but who knows.

**Comment by paulharris** [comment]
Ok, I'm about to move onto the new tool chain anyway, thanks :)
